const fs = require('fs');
const p = 'D:/mobile-app/app/src/screens/ApiHotToursScreen.tsx';
let s = fs.readFileSync(p, 'utf8');
const start = s.indexOf('  const loadHotTours = async () => {');
const end = s.indexOf('  const toggleCountryFilter = (country: Country) => {');
if (start < 0 || end < 0) {
  console.error('markers', start, end);
  process.exit(1);
}
const neu = [
  '  const loadHotTours = async () => {',
  '    if (!selectedDeparture) return;',
  '    if (hasFailedOnce) return;',
  '    if (isLoading) return;',
  '',
  '    try {',
  '      setIsLoading(true);',
  '      setHasFailedOnce(false);',
  '',
  '      const countryIds =',
  '        selectedCountries.length > 0',
  '          ? selectedCountries.map((c) => c.id)',
  '          : route?.params?.countryId',
  '            ? [Number(route.params.countryId)]',
  '            : undefined;',
  '',
  '      const params: HotToursParams = {',
  '        departureId: selectedDeparture.id,',
  "        currency: searchParams.currency || currency || 'RUB',",
  '        onlyCharter: !!searchParams.onlyCharter,',
  '        limit: 80,',
  '        countryIds,',
  '      };',
  '',
  '      let hots: TourHot[] = [];',
  '      try {',
  '        const remote = await fetchHotToursViaBackend(params);',
  '        if (remote.success && remote.data?.length) {',
  '          hots = remote.data;',
  '        }',
  '      } catch (e) {',
  "        logger.debug('[HotTours] backend:', (e as Error)?.message);",
  '      }',
  '      if (!hots.length) {',
  '        try {',
  '          const legacy = await tourvisorApi.getHotTours(params);',
  '          hots = Array.isArray(legacy) ? legacy : [];',
  '        } catch (e) {',
  "          logger.debug('[HotTours] legacy:', (e as Error)?.message);",
  '        }',
  '      }',
  '',
  '      const uniqueHotels = tourHotsToTourHotels(hots);',
  '      if (uniqueHotels.length === 0) {',
  '        setHasFailedOnce(true);',
  "        logger.warn('[HotTours] No tours found');",
  '      }',
  '',
  '      setHotTours(uniqueHotels);',
  '      if (uniqueHotels.length > 0) {',
  '        preCacheTourDetailsFromSearchResults(uniqueHotels, params.currency).catch(() => {});',
  '        const cacheKey = `hot_v2_${selectedDeparture.id}_${(countryIds || []).join(\',\')}`;',
  '        cacheService.set(CacheType.HOT_TOURS, cacheKey, uniqueHotels).catch(() => {});',
  '        if (!promoNotificationSent.current) {',
  '          const first = uniqueHotels[0];',
  '          const firstTour = first?.tours?.[0];',
  '          const tourName = firstTour',
  '            ? `${first.name}, ${first.country?.name || \'\'}`',
  "            : first?.name || 'Акционный тур';",
  '          notificationService.sendPromoTourNotification(tourName, firstTour?.id?.toString()).catch(() => {});',
  '          promoNotificationSent.current = true;',
  '        }',
  '      }',
  '    } catch (error: any) {',
  '      setHasFailedOnce(true);',
  '      if (hotTours.length === 0) {',
  '        setHotTours([]);',
  '      }',
  '    } finally {',
  '      setIsLoading(false);',
  '    }',
  '  };',
  '',
  '',
].join('\n');
s = s.slice(0, start) + neu + s.slice(end);
fs.writeFileSync(p, s);
console.log('ok');
